apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tomcat-static
  labels:
    app: tomcat-static 
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat-static
    spec:
      hostname: tomcat-static
      containers:
      - name: tomcat-static
        image: complete-repo-path
        env:
        - name: ES_JAVA_OPTS
          value: -XX:UseAVX=2 -XX:-AssumeMP -Xms2048m -Xmx2048m 
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 1
            memory: 1500Mi
          limits:
            cpu: 2
            memory: 3000Mi
        ports:
        - containerPort: 8080
          name: api
        volumeMounts:
        - name: data
          mountPath: /usr/local/tomcat7/webapps
        - name: config
          mountPath: /usr/local/tomcat7/conf/ROOT
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tomcat-static
      - name: config
        configMap: 
          name: tomcat-static
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "uid"
              fieldRef:
                fieldPath: metadata.uid
