apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-static
  labels:
    app: tomcat-static
spec:
  # storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80G
