apiVersion: v1
kind: Service
metadata:
  name: tomcat-static
  namespace:
  labels:
    app: tomcat-static
spec:
  type: LoadBalancer
  ports:
  - name: "api"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: tomcat-static
